### ISSUE TITLE
Does not work with google universal tracking code

### ISSUE THREAD

**Issue by mattwhetton** [auth0/auth0-analytics.js#17]
Tried following the instructions on the Auth0 website, but cannot get this working with google analytics, when analytics is registered using google universal tracking code.

Cant even really tell if google analytics is actually supported anymore?

The error I get is: “Invalid tracking Id. Aborting hit.” 

Like this person on Stack Overflow: https://stackoverflow.com/questions/24772574/invalid-tracking-id-aborting-hit-for-event-tracking

**Comment by francocorreasosa** [comment]
Hi @mattwhetton, thanks for reporting this. We'll look into it and keep you posted.

**Comment by mattwhetton** [comment]
No problem. I think also now the default google tracking code might be the new google tag manager version, which again has a different syntax

**Comment by francocorreasosa** [comment]
Yeah, I was going to ask you about that actually. Can you try using `google-tag-manager` instead of `google-analytics`? We also support it.

**Comment by francocorreasosa** [comment]
If that works for you, we will update the documentation to clarify it :)

**Comment by francocorreasosa** [comment]
I will close this issue since we've got no response. Feel free to reopen it if you still have the problem.

**Comment by luke-siedle** [comment]
I had a related issue I tracked down to a problem in auth0-tag-manager library. Master is up to date but there's no new release in npm, and the CDN version also has this bug. 

Here's the fix that's already in place: https://github.com/auth0/auth0-tag-manager/commit/d83ee8e3d2349d21eddc2e072f2b345874d9cd72#diff-104cef01154fd0dac61f04d87aeeeb2e

The change is `config.preloaded`, which needs to be set to true if you've already got GA in your environment. This is also specified in the documentation here. The code was previously reinitialising GA if preloaded was set to true. 

https://auth0.com/docs/analytics/integrations/google-analytics

Presumably you can just supply the tracking code to get around this, but since this is well documented it makes it a bit confusing when it doesn't work.
